// Game-domain tables (PRD §7.6). Auth tables live in ./auth.ts (generated by better-auth).
import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import { user } from "./auth";

/** Ruleset as stored (mirrors `@carcassonne/protocol` Ruleset; kept local so db has no protocol dep). */
export type RulesetJson = {
  fieldEdition: 1 | 2 | 3;
  river: boolean;
  abbot: boolean;
  handSize: number;
};

/** Clock settings (PRD §6.6). */
export type ClockJson =
  | { type: "none" }
  | { type: "turn"; turnSeconds: number }
  | { type: "bank"; bankSeconds: number; incrementSeconds: number };

export type BotTier = "easy" | "medium" | "hard" | "expert";

/** One seat in a room lobby. Guests are identified by a signed guest id. */
export type RoomSeatJson =
  | { kind: "human"; userId: string | null; guestId: string | null; name: string }
  | { kind: "bot"; tier: BotTier; name: string };

export type ScoreBreakdownJson = {
  road: number;
  city: number;
  cloister: number;
  garden: number;
  field: number;
};

export const profile = pgTable("profile", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  displayName: text("display_name").notNull(),
  avatar: text("avatar"),
  colorPref: text("color_pref"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

/** Glicko-2 rating per ranked queue. mu/phi are on the Glicko-2 scale (display = 1500 + 173.7178·mu). */
export const rating = pgTable(
  "rating",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    queue: text("queue").$type<"ffa3" | "ffa4">().notNull(),
    mu: doublePrecision("mu").notNull().default(0),
    phi: doublePrecision("phi").notNull().default(350 / 173.7178),
    sigma: doublePrecision("sigma").notNull().default(0.06),
    games: integer("games").notNull().default(0),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.queue] })],
);

export const room = pgTable(
  "room",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    code: text("code").notNull(),
    /** Host: a user id or a guest id (`g_…`). */
    hostId: text("host_id").notNull(),
    ruleset: jsonb("ruleset").$type<RulesetJson>().notNull(),
    clock: jsonb("clock").$type<ClockJson>().notNull().default({ type: "none" }),
    maxPlayers: integer("max_players").notNull().default(5),
    /** Ordered seats (humans and bots). */
    seats: jsonb("seats").$type<RoomSeatJson[]>().notNull().default([]),
    status: text("status").$type<"lobby" | "playing" | "closed">().notNull().default("lobby"),
    ranked: boolean("ranked").notNull().default(false),
    gameId: uuid("game_id"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [uniqueIndex("room_code_uq").on(t.code)],
);

export const game = pgTable(
  "game",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    roomId: uuid("room_id").references(() => room.id, { onDelete: "set null" }),
    engineVersion: text("engine_version").notNull(),
    /** u64 seed as a decimal string (JS numbers cannot hold it). */
    seed: text("seed").notNull(),
    ruleset: jsonb("ruleset").$type<RulesetJson>().notNull(),
    clock: jsonb("clock").$type<ClockJson>().notNull().default({ type: "none" }),
    players: integer("players").notNull(),
    ranked: boolean("ranked").notNull().default(false),
    queue: text("queue").$type<"ffa3" | "ffa4">(),
    status: text("status").$type<"playing" | "ended" | "aborted">().notNull().default("playing"),
    /** Number of committed moves (= next ply). Denormalised for cheap polling. */
    ply: integer("ply").notNull().default(0),
    turnStartedAt: timestamp("turn_started_at", { withTimezone: true }),
    turnDeadline: timestamp("turn_deadline", { withTimezone: true }),
    finalScores: jsonb("final_scores").$type<number[]>(),
    startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true }),
  },
  (t) => [index("game_status_idx").on(t.status)],
);

export const gamePlayer = pgTable(
  "game_player",
  {
    gameId: uuid("game_id")
      .notNull()
      .references(() => game.id, { onDelete: "cascade" }),
    seat: integer("seat").notNull(),
    userId: text("user_id").references(() => user.id, { onDelete: "set null" }),
    guestId: text("guest_id"),
    name: text("name").notNull(),
    botTier: text("bot_tier").$type<BotTier>(),
    color: text("color").notNull(),
    /** Remaining bank time for chess-style clocks. */
    bankMs: bigint("bank_ms", { mode: "number" }),
    consecutiveTimeouts: integer("consecutive_timeouts").notNull().default(0),
    /** Set after 3 consecutive timeouts; a bot (Easy) takes over the seat. */
    afk: boolean("afk").notNull().default(false),
    finalScore: integer("final_score"),
    placement: integer("placement"),
    breakdown: jsonb("breakdown").$type<ScoreBreakdownJson>(),
  },
  (t) => [
    primaryKey({ columns: [t.gameId, t.seat] }),
    index("game_player_user_idx").on(t.userId),
  ],
);

/** The move log. PK (game_id, ply) is the compare-and-set that serialises concurrent intents. */
export const move = pgTable(
  "move",
  {
    gameId: uuid("game_id")
      .notNull()
      .references(() => game.id, { onDelete: "cascade" }),
    ply: integer("ply").notNull(),
    seat: integer("seat").notNull(),
    payload: jsonb("payload").notNull(),
    /** Engine events emitted by this move (cached so fan-out and polling never replay). */
    events: jsonb("events").notNull().default([]),
    /** "player" | "timeout" | "bot" */
    source: text("source").notNull().default("player"),
    at: timestamp("at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [primaryKey({ columns: [t.gameId, t.ply] })],
);

export const queueTicket = pgTable(
  "queue_ticket",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    queue: text("queue").$type<"ffa3" | "ffa4">().notNull(),
    rating: doublePrecision("rating").notNull(),
    status: text("status").$type<"waiting" | "matched" | "cancelled">().notNull().default("waiting"),
    gameId: uuid("game_id"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("queue_ticket_wait_idx").on(t.queue, t.status, t.createdAt),
    // One waiting ticket per user.
    uniqueIndex("queue_ticket_one_waiting_uq")
      .on(t.userId)
      .where(sql`${t.status} = 'waiting'`),
  ],
);

/** Function instance live time, to estimate provisioned-memory GB-hours (PRD §7.3 guard rails). */
export const instanceUsage = pgTable(
  "instance_usage",
  {
    instanceId: text("instance_id").primaryKey(),
    month: text("month").notNull(), // "YYYY-MM"
    startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(),
    lastHeartbeat: timestamp("last_heartbeat", { withTimezone: true }).defaultNow().notNull(),
    peakSockets: integer("peak_sockets").notNull().default(0),
  },
  (t) => [index("instance_usage_month_idx").on(t.month)],
);

/** Monthly server-bot CPU counter (PRD §7.3 bots). */
export const botCpuUsage = pgTable("bot_cpu_usage", {
  month: text("month").primaryKey(), // "YYYY-MM"
  cpuMs: bigint("cpu_ms", { mode: "number" }).notNull().default(0),
  moves: integer("moves").notNull().default(0),
});

/** Socket presence with a TTL heartbeat (stale after 30 s). */
export const presence = pgTable(
  "presence",
  {
    connId: text("conn_id").primaryKey(),
    gameId: uuid("game_id").notNull(),
    instanceId: text("instance_id").notNull(),
    userId: text("user_id"),
    guestId: text("guest_id"),
    seat: integer("seat"),
    name: text("name").notNull(),
    lastSeen: timestamp("last_seen", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [index("presence_game_idx").on(t.gameId, t.lastSeen)],
);
